services:
  - type: web
    name: PasteBin
    env: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        value: "jdbc:postgresql://dpg-d5a8hfili9vc73b1mk2g-a.virginia-postgres.render.com:5432/pastebin_db_7ffx"
      - key: DB_USERNAME
        value: "sumithra"
      - key: DB_PASSWORD
        value: "P0lo9y5GKHyd279v8Hlr7qc3BMEIBdzH"
