services:
  - type: web
    name: PasteBin
    env: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        value: "jdbc:mysql://<your-server-host>:3306/pastebin_db?useSSL=false&serverTimezone=UTC"
      - key: DB_USERNAME
        value: "root"
      - key: DB_PASSWORD
        value: "1234"
      - key: PORT
        value: "8080"
